export * as SERVICE_AUTH from './auth.service';
export * as SERVICE_PARTNER from './partner.service';
export * as SERVICE_PROGRAM from './program.service';
export * as SERVICE_KONSTITUEN from './konstituen.service';
export * as SERVICE_CITY from './city.service';
export * as SERVICE_PROVINCE from './province.service';
export * as SERVICE_VILLAGE from './village.service';
export * as SERVICE_DISTRICT from './district.service';
export * as SERVICE_TPS from './tps.service';
